/* A small curated list for the Emoji extension's suggestion popup (":" trigger). The
   playground demo pulls its list from a local project file that isn't published with the
   package, so this is our own — same shape @tiptap/extension-emoji expects. Extend freely. */
export const EMOJI_LIST = [
  { name: "grinning", emoji: "😀", shortcodes: ["grinning"], tags: ["happy", "smile"] },
  { name: "smile", emoji: "😄", shortcodes: ["smile"], tags: ["happy"] },
  { name: "joy", emoji: "😂", shortcodes: ["joy"], tags: ["laugh"] },
  { name: "wink", emoji: "😉", shortcodes: ["wink"], tags: [] },
  { name: "thinking", emoji: "🤔", shortcodes: ["thinking"], tags: ["hmm"] },
  { name: "neutral_face", emoji: "😐", shortcodes: ["neutral_face"], tags: [] },
  { name: "slightly_frowning_face", emoji: "🙁", shortcodes: ["frowning"], tags: ["sad"] },
  { name: "cry", emoji: "😢", shortcodes: ["cry"], tags: ["sad"] },
  { name: "angry", emoji: "😠", shortcodes: ["angry"], tags: [] },
  { name: "astonished", emoji: "😲", shortcodes: ["astonished"], tags: ["wow"] },
  { name: "heart_eyes", emoji: "😍", shortcodes: ["heart_eyes"], tags: ["love"] },
  { name: "thumbsup", emoji: "👍", shortcodes: ["+1", "thumbsup"], tags: ["approve", "good"] },
  { name: "thumbsdown", emoji: "👎", shortcodes: ["-1", "thumbsdown"], tags: [] },
  { name: "clap", emoji: "👏", shortcodes: ["clap"], tags: ["applause"] },
  { name: "wave", emoji: "👋", shortcodes: ["wave"], tags: ["hello", "bye"] },
  { name: "pray", emoji: "🙏", shortcodes: ["pray"], tags: ["please", "thanks"] },
  { name: "muscle", emoji: "💪", shortcodes: ["muscle"], tags: ["strong"] },
  { name: "fire", emoji: "🔥", shortcodes: ["fire"], tags: ["hot"] },
  { name: "tada", emoji: "🎉", shortcodes: ["tada"], tags: ["party", "celebrate"] },
  { name: "sparkles", emoji: "✨", shortcodes: ["sparkles"], tags: [] },
  { name: "star", emoji: "⭐", shortcodes: ["star"], tags: [] },
  { name: "heart", emoji: "❤️", shortcodes: ["heart"], tags: ["love"] },
  { name: "white_check_mark", emoji: "✅", shortcodes: ["check", "done"], tags: ["done", "ok"] },
  { name: "x", emoji: "❌", shortcodes: ["x"], tags: ["no", "wrong"] },
  { name: "warning", emoji: "⚠️", shortcodes: ["warning"], tags: ["caution"] },
  { name: "question", emoji: "❓", shortcodes: ["question"], tags: [] },
  { name: "exclamation", emoji: "❗", shortcodes: ["exclamation"], tags: [] },
  { name: "bulb", emoji: "💡", shortcodes: ["bulb"], tags: ["idea"] },
  { name: "memo", emoji: "📝", shortcodes: ["memo"], tags: ["note", "write"] },
  { name: "clipboard", emoji: "📋", shortcodes: ["clipboard"], tags: [] },
  { name: "file_folder", emoji: "📁", shortcodes: ["folder"], tags: [] },
  { name: "page_facing_up", emoji: "📄", shortcodes: ["page"], tags: ["document"] },
  { name: "email", emoji: "📧", shortcodes: ["email"], tags: ["mail"] },
  { name: "calendar", emoji: "📅", shortcodes: ["calendar"], tags: ["date"] },
  { name: "clock", emoji: "🕒", shortcodes: ["clock"], tags: ["time"] },
  { name: "pushpin", emoji: "📌", shortcodes: ["pushpin"], tags: ["pin"] },
  { name: "lock", emoji: "🔒", shortcodes: ["lock"], tags: ["secure"] },
  { name: "unlock", emoji: "🔓", shortcodes: ["unlock"], tags: [] },
  { name: "moneybag", emoji: "💰", shortcodes: ["money"], tags: [] },
  { name: "chart_increasing", emoji: "📈", shortcodes: ["chart_up"], tags: ["growth"] },
  { name: "chart_decreasing", emoji: "📉", shortcodes: ["chart_down"], tags: [] },
  { name: "rocket", emoji: "🚀", shortcodes: ["rocket"], tags: ["launch"] },
  { name: "eyes", emoji: "👀", shortcodes: ["eyes"], tags: ["look"] },
  { name: "raised_hand", emoji: "✋", shortcodes: ["stop"], tags: [] },
  { name: "handshake", emoji: "🤝", shortcodes: ["handshake"], tags: ["deal", "agree"] },
  { name: "office", emoji: "🏢", shortcodes: ["office"], tags: ["building"] },
  { name: "globe", emoji: "🌐", shortcodes: ["globe"], tags: ["world"] },
];
